version: '2'

services:
  exporter:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/binaries/EchangeExporterProto/EchangeExporterProto.exe", "--help"]
    volumes:
      - dot-nuget:/root/.nuget
      - nuget-cache:/root/.local/share/NuGet/Cache

volumes:
  dot-nuget:
    external:
      name: ./CACHE/dot-nuget
  nuget-cache:
    external:
      name: ./CACHE/nuget-cache
