version: '2'

services:
  exporter:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/binaries/EchangeExporterProto/EchangeExporterProto.exe", "--config", "/config/exporter.config", "--targets", "/config/targets.csv"]
    volumes:
      - $PWD:/config
