// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Messages")]
[assembly: AssemblyProductAttribute("ExchangeExporterProto")]
[assembly: AssemblyDescriptionAttribute("Export exchange accounts including appointments and contacts")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyCompanyAttribute("linagora")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
        internal const string InformationalVersion = "1.0";
    }
}
